logging:
  level:
    root: INFO

server:
  port: 8081
spring:
  application:
    name: payments-mic
  sleuth:
    sampler:
      rate: 50
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/
  cloud:
    stream:
      function:
        definition: offlinePayment;onlinePayment
      kafka:
        binder:
          brokers: "localhost:29092"
          zkNodes: "localhost:2181"
        bindings:
          offlinePayment-in-0:
            consumer:
              enableDlq: true
              dlqName: offline.dlq
          onlinePayment-in-0:
            consumer:
              enableDlq: true
              dlqName: online.dlq
      bindings:
        offlinePayment-in-0:
          destination: offline
          group: offline-payments-gr
          consumer:
            maxAttempts: 4
            retryableExceptions:
              com:
                wefox:
                  clothingCompany:
                    exceptions:
                      BusinessException: false
        onlinePayment-in-0:
          destination: online
          group: online-payments-gr
          consumer:
            maxAttempts: 4
            retryableExceptions:
              com:
                wefox:
                  clothingCompany:
                    exceptions:
                      BusinessException: false

